# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = "ubuntu/trusty64"
        ubuntu.vm.hostname = "ubuntu"

        ubuntu.vm.network "private_network", ip: "192.168.33.24"

        ubuntu.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "512"]
            vb.customize ["modifyvm", :id, "--cpus", "2"]
        end
    end
end
